### PR TITLE
Update Open-science-schedule.md

### PR DESCRIPTION
**Pull request by marcosvital**
Added some more sessions.

### CODE REVIEW

**Comment by marcosvital** [comment]
Oops, just realized you worked on the first one, so it might be even more conflicts with this! 
Anyway, don't worry about resolving conflicts (I'm not good at that either!), just go ahead and grab the new info. ;)

**Comment by npscience** [comment]
Sorry @marcosvital ! I've now added a list at the top so we can say which ones we're working on. Or we can chat here :)

I'm doing decentralization Saturday at the mo. Do you want to do open innovation Sunday?

I'll port any updates from this PR into my version, don't worry about redoing anything.

**Comment by marcosvital** [comment]
No problem!

OK, I'll for open innovation on Sunday. :D

**Comment by npscience** [comment]
Closing now :)

**Pull request closed without merging**
